apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
  - quota.yaml
  - netpol.yaml
images:
  - name: PLACEHOLDER_IMAGE
    newName: 707258693637.dkr.ecr.us-east-1.amazonaws.com/boi-api-gateway
    newTag: latest
replicas:
  - name: boi-api-gateway
    count: 3
  - name: boi-auth-service
    count: 3
  - name: boi-account-service
    count: 3
  - name: boi-transaction-service
    count: 3
