server:
  port: 8083

spring:
  application:
    name: boi-transaction-service
  datasource:
    url: ${DB_URL:jdbc:h2:mem:transactions;DB_CLOSE_DELAY=-1}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
