- op: replace
  path: /spec/template/spec/containers/0/image
  value: ealen/echo-server:latest
- op: replace
  path: /spec/template/spec/containers/0/ports/0/containerPort
  value: 80
- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/httpGet/path
  value: /
- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/httpGet/port
  value: 80
- op: replace
  path: /spec/template/spec/containers/0/readinessProbe/httpGet/path
  value: /
- op: replace
  path: /spec/template/spec/containers/0/readinessProbe/httpGet/port
  value: 80
- op: replace
  path: /spec/template/spec/containers/0/securityContext/readOnlyRootFilesystem
  value: false
